Baklol_TV/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from Baklol_TV import settings
from articlesapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.trending,name="homepage"),
    path('about/',TemplateView.as_view(template_name="about_us.html"),name="about"),
    path('meet_our_developers/',TemplateView.as_view(template_name="developers.html"),name="meet_our_developers"),
    path('terms_and_conditions/',TemplateView.as_view(template_name="TermsAndConditions.html"),name="terms_and_conditions"),
    path('privacy_policy/',TemplateView.as_view(template_name="PrivacyPolicy.html"),name="privacy_policy"),
    path('', include('articlesapp.urls')),
    path('', include('videosapp.urls')),
    path('', include('memesapp.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articlesapp/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from articlesapp import views

app_name = "articlesapp"
urlpatterns = [
    path('stories/',views.stories,name="homepage"),
    path('single_article/<int:id>',views.single_article,name="single_article"),
    path('single_carousel_article/<int:id>',views.single_carousel_article,name="single_carousel_article"),
    path('search_article/',views.search_article,name="search_article"),

]

memesapp/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from memesapp import views

app_name = "memesapp"
urlpatterns = [
    path('memes/',views.memes_home,name="homepage"),
    path('single_meme/<int:id>',views.single_meme,name="single_meme")

]

videosapp/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from videosapp import views

app_name = "videosapp"
urlpatterns = [
    path('videos/',views.videos,name="homepage"),

]

articlesapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ArticlesModel(models.Model):
    tittle = models.CharField(max_length=400)
    category = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="article_images/")
    is_trending = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    post_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.tittle

class CarouselModel(models.Model):
    tittle = models.CharField(max_length=400)
    category = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="article_images/")
    is_published = models.BooleanField(default=False)
    post_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.tittle

memesapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MemesModel(models.Model):
    tittle = models.CharField(max_length=200)
    image = models.ImageField(upload_to='memes/')
    post_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.tittle

videosapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class VideosModel(models.Model):
    tittle = models.CharField(max_length=400,default=False)
    link = models.URLField()
    is_published = models.BooleanField()
    is_trending = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.tittle

articlesapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from articlesapp.models import *
from videosapp.models import *
import itertools
from django.db.models import Q

# Create your views here.
def trending(request):
    data = ArticlesModel.objects.filter(is_trending=True,is_published=True)
    carousel_data = CarouselModel.objects.filter(is_published=True)
    videos = VideosModel.objects.filter(is_published=True,is_trending=True)
    trending_videos = itertools.islice(videos, 15)
    res = list(itertools.islice(reversed(carousel_data), 0, 3))
    l = []
    for x in  res:
        l.append(x)

    slide1 = l[0]
    slide2 = l[1]
    slide3 = l[2]
    paginator = Paginator(data, 40)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {"page_obj":page_obj,"trending_videos":trending_videos,"slide1":slide1,"slide2":slide2,"slide3":slide3}
    return render(request,"homepage.html",context)


def stories(request):
    articles_data = ArticlesModel.objects.filter(is_published=True)
    carousel_data = CarouselModel.objects.filter(is_published=True)
    res = list(itertools.islice(reversed(carousel_data), 0, 3))
    l = []
    for x in res:
        l.append(x)
    slide1 = l[0]
    slide2 = l[1]
    slide3 = l[2]

    paginator = Paginator(articles_data, 60)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {"page_obj":page_obj,"slide1":slide1,"slide2":slide2,"slide3":slide3}
    return render(request,"articles_templates/article_homepage.html",context)


def single_article(request,id):
    article = ArticlesModel.objects.get(id=id)
    trending_data = ArticlesModel.objects.filter(is_trending=True, is_published=True)
    top10 = itertools.islice(trending_data, 10)
    context = {"article": article,"trending_data":top10}

    return render(request,"articles_templates/single_article.html",context)


def single_carousel_article(request,id):
    article = CarouselModel.objects.get(id=id)
    trending_data = ArticlesModel.objects.filter(is_trending=True, is_published=True)
    top10 = itertools.islice(trending_data, 10)
    context = {"article": article, "trending_data": top10}

    return render(request, "articles_templates/single_article.html", context)


def search_article(request):
    s = request.POST.get("search")
    if s:
        src = ArticlesModel.objects.filter(Q(tittle__icontains=s) | Q(category__icontains=s))
        if src:
            return render(request, "articles_templates/search.html", {"src": src,"search":s})
        else:
            return render(request,"articles_templates/search.html",{"message":" Sorry we couldn't find any matches for, "+s,"search":s})
    else:
        return redirect("homepage")

memesapp/views.py
from django.shortcuts import render
from memesapp.models import *

# Create your views here.
def memes_home(request):
    memes = MemesModel.objects.all()
    context ={"memes":memes}
    return render(request,"memes_templates/memes_homepage.html",context)


def single_meme(request,id):
    meme = MemesModel.objects.get(id=id)

    return render(request,"memes_templates/single_meme.html",{"meme":meme})

videosapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from videosapp.models import *

# Create your views here.
def videos(request):
    videos_data = VideosModel.objects.filter(is_published=True)

    paginator = Paginator(videos_data, 30)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={"page_obj":page_obj}
    return render(request,"videos_templates/videos_homepage.html",context)

templates/about_us.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}

    <div class="container">

    <br><br>
        <h1 style="font-size: 24px;font-weight: 500;text-align: center;font-family: Roboto, sans-serif;color: #2874f0">ABOUT US</h1><br><br>
        <div style="text-align: center">

            <img src="{% static 'images/baklol 1 (1).png' %}" width="30%">
        </div>
        <br><br><br>
        <div class="row">
            <div class="col-sm-12" style="padding: 2% 5%;text-align: justify">
                <p style="font-family: Roboto, sans-serif"> Wanna remain well-informed but can't because long articles and non-sense narrations bore you? </p>

                <p style="font-family: Roboto, sans-serif"> We're here to the rescue. At BaK-LoL TV, we provide you factual, source-based information on political, economic, social development issues and current affairs with a twist of entertainment. We laugh and have fun but never at the expense of someone's reputation.  </p>

                <p style="font-family: Roboto, sans-serif">  We have no political or religious affiliations. What matters most to us is that our audience is well-informed and does not fall prey to power hungry rumor and hate mongers. And with this aim in mind, we go through all perspectives and double check the information before we present it to you using creative means. We sing for you. We dance for you! We act for you! We CREATE for you!  </p>

                <p style="font-family: Roboto, sans-serif"> Though our main focus area is the issues in Jammu and Kashmir, we also cover topics of global and national importance occasionally. Our work also aims to connect you to inspiring people from all fields. From artists to politicians, we interview them all, asking them questions that we believe you should know the answers of! </p>

                <p style="font-family: Roboto, sans-serif">  And public opinion? We bring that to you as well! </p>

            </div>

        </div>

    </div>


{% endblock %}

templates/articles_templates/article_homepage.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}

    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        <a href="{% url 'articlesapp:single_carousel_article' slide1.id %}"><img src="{{ slide1.image.url }}" class="d-block w-100" alt="{{ slide1.tittle }}"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide1.category }}</h5>
        <p>{{ slide1.tittle }}</p>
      </div>
    </div>
    <div class="carousel-item">
        <a href="{% url 'articlesapp:single_carousel_article' slide2.id %}"><img src="{{ slide2.image.url }}" class="d-block w-100" alt="{{ slide2.tittle }}"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide2.category }}</h5>
        <p>{{ slide3.tittle }}</p>
      </div>
    </div>
    <div class="carousel-item">
        <a href="{% url 'articlesapp:single_carousel_article' slide3.id %}"><img src="{{ slide3.image.url }}" class="d-block w-100" alt="{{ slide3.tittle }}"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide3.category }}</h5>
        <p>{{ slide3.tittle }}</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>

    <div class="content-header">
                <h5><img src="{% static 'icons/menu.png' %}">  STORIES</h5><hr>
        </div>

    <div class="container">
        <div class="row">
            {% for x in page_obj %}
            <div class="col-sm-3">
                <a href="{% url 'articlesapp:single_article' x.id %}">
                <div class="card">
                    <img src="{{ x.image.url }}" class="card-img-top" alt="{{ x.tittle }}">
                    <div class="card-body">
                        <h6>{{ x.category }}</h6>
                        <h5 class="card-text">{{ x.tittle }}</h5>
                        <span style="color: #2874f0">{{ x.author.first_name }} {{ x.author.last_name }}</span>
                        <span> | {{ x.post_date.date }} {{ x.post_date.time }}</span>
                    </div>
                </div>
                </a>
            </div>
            {% endfor %}

            <span style="text-align: center">
                {% if page_obj.has_previous %}
                <br><a href="?page={{ page_obj.previous_page_number }}" style="text-decoration: none;font-weight: 500;letter-spacing: 1px;">
                <img src="{% static 'icons/left-arrow.png' %}" width="14"> Previous
                </a>
                {% endif %}
            &nbsp; &nbsp; &nbsp;
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" style="text-decoration: none;font-weight: 500;letter-spacing: 1px">
                  Next <img src="{% static 'icons/right-arrow.png' %}" width="14">
                </a>
                {% endif %}
            </span>
        </div>
    </div>


{% endblock %}

templates/articles_templates/search.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}
    <div class="content-header">
        <h5><img src="{% static 'icons/search.png' %}">  &nbsp; {{ search }}</h5><hr>
    </div>
    <div class="container">
        {% if src %}
        <div class="row">
            {% for y in src %}
            <div class="col-sm-3">
                <a href="{% url 'articlesapp:single_article' y.id %}">
                <div class="card" style="width: 16rem;">
                    <img src="{{ y.image.url }}" class="card-img-top" alt="{{ y.tittle }}">
                    <div class="card-body">
                        <h6>{{ y.category }}</h6>
                        <h5 class="card-text">{{ y.tittle }}</h5>
                        <span style="color: #2874f0">{{ y.author }}</span>
                        <span> | {{ y.post_date.date }} {{ y.post_date.time }}</span>
                    </div>
                </div>
                </a>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if message %}
            <br>
            <img src="{% static 'icons/not-found.png' %}" style="margin-left: 46%"><br><br>
            <div style="text-align: center">
                <span style="font-weight: 500;font-size: 16px">{{ message }}</span>
            </div>

            <br>
        {% endif %}
    </div>

{% endblock %}

templates/articles_templates/single_article.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}

    <div class="container">

    <div class="content-header">
        <h5 style="font-size: 24px"><img src="{% static 'icons/menu.png' %}">  {{ article.tittle }}</h5><hr>
    </div>
        <div class="row">
            <div class="col-md-8">
                <div class="article-card">
                    <div class="card-body">
                        <img src="{{ article.image.url }}">
                        <br><br><hr>
                        <p id="article-p">{{ article.description }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="article-card">
                    <div class="card-body">
                        <div class="content-header">
                            <h5>  TRENDING</h5><hr>
                        </div>
                        {% for y in trending_data %}
                            <div class="col-sm-3">
                                <a href="{% url 'articlesapp:single_article' y.id %}">
                                    <div class="card" style="width: 16rem;">
                                        <img src="{{ y.image.url }}" class="card-img-top" alt="{{ y.tittle }}">
                                        <div class="card-body">
                                            <h6>{{ y.category }}</h6>
                                            <h5 class="card-text">{{ y.tittle }}</h5>
                                            <span style="color: #2874f0">{{ y.author }}</span>
                                            <span> | {{ y.post_date.date }} {{ y.post_date.time }}</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_package_v0.16/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_package_v0.16/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_package_v0.16/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon_package_v0.16/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon_package_v0.16/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css">

    <title>BaK-LoL TV</title>
  </head>
  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid" style="margin-left: 5%">
            <a class="navbar-brand" href="{% url 'homepage' %}"><img src="{% static 'images/baklol 1 (1).png' %}" width="50"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}" style="color: #2874f0">TRENDING &nbsp; &nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'videosapp:homepage' %}" style="color: #2874f0">VIDEOS &nbsp; &nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'articlesapp:homepage' %}" style="color: #2874f0">STORIES &nbsp; &nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'memesapp:homepage' %}" style="color: #2874f0">MEMES &nbsp; &nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}" style="color: #2874f0">ABOUT US</a>
                    </li>
                </ul>
                <form class="d-flex" action="{% url 'articlesapp:search_article' %}" method="post">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn-search" type="submit"><img src="{% static 'icons/search.png' %}"></button>
                </form>
            </div>
        </div>
     </nav>



        {% block content %}

        {% endblock %}
     <br>

     <hr>

    <footer>
        <div class="row">
            <div class="col-sm-3" id="footer-logo">
                <a href="{% url 'homepage' %}"><img src="{% static 'images/baklol 1 (1).png' %}" width="40%"></a>
            </div>
            <div class="col-sm-3">
                <h5><a href="">FOLLOW US</a></h5>
                <span id="social">
                    <a href="https://www.facebook.com/theBaklolTv" target="_blank"><img src="{% static 'icons/facebook (1).png' %}" ></a>
                    <a href="https://twitter.com/thebakloltv" target="_blank"><img src="{% static 'icons/twitter.png' %}" ></a>
                    <a href="https://www.instagram.com/thebakloltv_/" target="_blank"><img src="{% static 'icons/instagram (1).png' %}" ></a>
                    <a href="https://www.youtube.com/channel/UCLrypnmk7e7mf_lha5VlOtQ" target="_blank"><img src="{% static 'icons/youtube (1).png' %}" ></a>
                </span>
            </div>
            <div class="col-sm-3">
                <h5><a href="#">Mobile: +91-70513 25775</a></h5>
                <h5><a href="mailto:baklol@gmail.com">Email: baklol@gmail.com</a></h5>
            </div>
            <div class="col-sm-3">
                <h5><a href="{% url 'meet_our_developers' %}">Meet Our Developer Team</a></h5>
                <h5><a href="{% url 'terms_and_conditions' %}">Terms And Conditions</a></h5>
            </div>
        </div>
    </footer>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}

 <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        <a href="{% url 'articlesapp:single_carousel_article' slide1.id %}"><img src="{{ slide1.image.url }}" class="d-block w-100" alt="{{ slide1.tittle }}"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide1.category }}</h5>
        <p>{{ slide1.tittle }}</p>
      </div>
    </div>
    <div class="carousel-item">
        <a href="{% url 'articlesapp:single_carousel_article' slide2.id %}"><img src="{{ slide2.image.url }}" class="d-block w-100" alt="{{ slide2.tittle }}"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide2.category }}</h5>
        <p>{{ slide3.tittle }}</p>
      </div>
    </div>
    <div class="carousel-item">
        <a href="{% url 'articlesapp:single_carousel_article' slide3.id %}"><img src="{{ slide3.image.url }}" class="d-block w-100" alt="{{ slide3.tittle }}"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide3.category }}</h5>
        <p>{{ slide3.tittle }}</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>
    <br>
    <div class="content-header">
        <h5><img src="{% static 'icons/menu.png' %}">  STORIES</h5><hr>
    </div>
    <br>
    <div class="container">
        <div class="row">
            {% for y in page_obj %}
            <div class="col-sm-3">
                <a href="{% url 'articlesapp:single_article' y.id %}">
                <div class="card">
                    <img src="{{ y.image.url }}" class="card-img-top" alt="{{ y.tittle }}" width="100" height="200px">
                    <div class="card-body">
                        <h6>{{ y.category }}</h6>
                        <h5 class="card-text">{{ y.tittle }}</h5>
                        <span style="color: #2874f0">{{ y.author }}</span>
                        <span> | {{ y.post_date.date }} {{ y.post_date.time }}</span>
                    </div>
                </div>
                </a>
            </div>
            {% endfor %}

            <span style="text-align: center">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" style="text-decoration: none;font-weight: 500;letter-spacing: 1px;">
                <img src="{% static 'icons/left-arrow.png' %}" width="14"> Previous
                </a>
                {% endif %}
            &nbsp; &nbsp; &nbsp;
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" style="text-decoration: none;font-weight: 500;letter-spacing: 1px">
                  Next <img src="{% static 'icons/right-arrow.png' %}" width="14">
                </a>
                {% endif %}
            </span>

            <a href="{% url 'articlesapp:homepage' %}" style="text-decoration: none"><br><br><span style="font-size: 16px;font-weight: 600;color:#3498db">Go To Stories &nbsp; <img src="{% static 'icons/right.png' %}" width="20px"> </span></a>
        </div>
    </div>

    <div class="content-header">
        <br>
        <br>
        <h5><img src="{% static 'icons/menu.png' %}">  VIDEOS</h5><hr>
    </div>
    <br>
    <div class="container">
        <div class="row">
            {% for x in trending_videos %}
            <div class="col-md-4 meme-col">
                <iframe width="100%" height="200px" src="{{ x.link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            {% endfor %}

        <a href="{% url 'videosapp:homepage' %}" style="text-decoration: none"><br><br><span style="font-size: 16px;font-weight: 600;color:#3498db">Go To Videos &nbsp; <img src="{% static 'icons/right.png' %}" width="20px"> </span></a>


        </div>
    </div>


{% endblock %}

templates/memes_templates/memes_homepage.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}

    <br>

    <div class="container">
        <div class="content-header">
                <h5><img src="{% static 'icons/menu.png' %}">  MEMES</h5><hr>
        </div>
        <div class="row">
            {% for x in memes %}
            <div class="col-md-4 meme-col" style="padding: 2%">
                <h5>{{ x.tittle }}</h5>
                <div class="meme" style="padding: 5%">
                    <a href="{% url 'memesapp:single_meme' x.id  %}"><img src="{{ x.image.url }}"></a>
                </div>
            </div>
            {% endfor %}
        </div>



    </div>

    <br>
    <br>


{% endblock %}

templates/memes_templates/single_meme.html
{% extends 'base.html' %}
{% load  static %}

{% block  content%}

    <br>

    <div class="container">

        <div class="content-header">
            <h5><img src="{% static 'icons/menu.png' %}">  {{ meme.tittle }}</h5><hr>
        </div>
        <div class="single-meme" >
            <br>
            <img src="{{ meme.image.url }}" style="border: 1px solid grey;padding: 2%">

        </div>

    </div>

    <br>
    <br>


{% endblock %}